server:
  port: 8888

spring:
  config:
    activate:
      on-profile: local
  cloud:
    config:
      server:
        git:
          uri: https://github.com/KT-devs/p-sm-uxair1/config-service/src/main/java/local
          search-paths:
            - "{application}/{profile}"
        bootstrap: true
      discovery:
        enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}